# Generated by Django 4.2.25 on 2025-10-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_tag_post_category_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body_markdown',
            field=models.BooleanField(default=False, verbose_name='Format Markdown'),
        ),
    ]
